#!/usr/bin/env bash
#
#
#  minerboot - A script to set up and run NVIDIA miner(s) on boot
#
#  Copyright (C) 2019 LeshaCat
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

# CURRENT COIN NAMES (comma separated)
THECOINS="monero"

# AUTOMATICALLY RUN APT UPGRADE
AUTO_APT_UPGRADE=false

# REBOOT AFTER DRIVER UPGRADE
FORCE_REBOOT_AFTER_UPGRADE=false

# MONITOR AND RESTART MINERS
MONITOR_COINS=true

# MONITOR EVERY X SECONDS
MONITOR_INTERVAL=5
