#!/usr/bin/env bash
#
#
#  minerboot - A script to set up and run NVIDIA miner(s) on boot
#
#  Copyright (C) 2019 LeshaCat
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

# CURRENT COIN NAME (nano coins/COINNAME)
CURRENT_COIN="monero"

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

BDIR="$( cd "$(dirname "$0")" ; pwd -P )"
WDIR=$(pwd)

# Load our functions
source ${BDIR}/inc/functions.sh

logit "MinerBoot v0.1a Started!"

# Run our setup script
source ${BDIR}/inc/setup.sh

logit "MinerBoot v0.1a Finished!"


















