#!/usr/bin/env bash
#
#
#  minerboot - A script to set up and run NVIDIA miner(s) on boot
#
#  Copyright (C) 2019 LeshaCat
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#

# CURRENT COIN NAMES (comma separated)
THECOINS="monero"

FORCE_REBOOT_AFTER_NVIDIA_UPDATE=false

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Load our functions
source ${BDIR}/inc/functions.sh

BDIR="$( cd "$(dirname "$0")" ; pwd -P )"
WDIR=$(pwd)

logit "MinerBoot v0.1a Started!"

# Run our setup script
source ${BDIR}/inc/setup.sh

IFS=',' # space is set as delimiter
read -ra THE_COINS <<< "${THECOINS}"

for CURRENT_COIN in "${THE_COINS[@]}"
do

    logit "Starting miner for ${CURRENT_COIN}"
    if [ ! -f ${BDIR}/miners/${CURRENT_COIN} ] ; then
        logit "File ${BDIR}/miners/${CURRENT_COIN} does not exist!"
        logit "Skipping coin ${CURRENT_COIN}!"
    else
        source ${BDIR}/miners/${CURRENT_COIN}
        
        if [ -z "$MINERLOG" ] ; then MINERLOG=/dev/null; fi    
        
        $MINERCMD 2>&1 > ${MINERLOG} &
        
        logit "Miner started for ${CURRENT_COIN} PID: ${!}"
        
        echo "${!}" > ${BDIR}/tmp/${CURRENT_COIN}.pid
    fi
    
done
    
    

# logit "Monitoring miner(s) ${THECOINS}"

# MONITOR MINERS BY PID LIST

# RESTART MINERS IF FAIL


logit "MinerBoot v0.1a Finished!"


















